FROM nginx:latest

# Создание директории для хранения изображений
RUN mkdir /usr/share/nginx/html/images

# Установка прав доступа (в зависимости от вашей конфигурации)
RUN chmod -R 777 /usr/share/nginx/html/images