port: "8080"

postgres:
  username: "postgres"
  #host: "db"
  host: localhost
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

cache:
  username: "default"
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  #host: "cache"
  host: "localhost"
  port: "6379"
  dbnumber: 0

pubsub:
  username: "default"
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  #host: "pubsub"
  host: "localhost"
  port: "6380"
  dbnumber: 0

minio:
  #endpoint : "minio-server:9000"
  endpoint : "localhost:9000"
  keyID : "user"
  accessKey : "password"
